version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: PHPOffice:master    # Required. Must be in the same fork network.
    assignees:              # Optional
      - cHeeSaW
      - cawolf
      - mmross
    reviewers:              # Optional
      - cHeeSaW
      - cawolf
      - mmross
      
